name:                tftp-server
version:             0.1.0.0
github:              "lipusal/haskell-tftp-server"
license:             BSD3
author:              "Juan Li Puma"
maintainer:          "example@example.com"
copyright:           "2019 Juan Li Puma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lipusal/haskell-tftp-server#readme>

dependencies:
- base >= 4.12 && < 5
- network-house

library:
  source-dirs: src

executables:
  tftp-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tftp-server

tests:
  tftp-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tftp-server
